export type { TextEntity, TextSummary } from "./text";
export type { SentenceEntity, SentenceSummary } from "./sentence";
export type { LemmaEntity, LemmaSummary } from "./lemma";
export type { WordFormEntity, WordFormSummary } from "./word-form";
export type { EndingEntity, EndingSummary } from "./ending";
export type { CaseEntity, CaseSummary } from "./case";
export type { ConceptEntity, ConceptSummary } from "./concept";
export type { ExpressionEntity, ExpressionSummary } from "./expression";
export type { CollocationEntity, CollocationSummary } from "./collocation";
